version: '3.7'

services:

  collector:
    build: ./collector/app/
    environment:
      PYTHONUNBUFFERED: 1
      LOGLEVEL: INFO
      DOMAINSOURCE: domainfile
      DOMAINFILE: /data/domains.txt
    volumes:
      - ./collector/app:/app
      - ./collector/data:/data
      - ./shared:/shared
    depends_on:
      - recursor
      - dnssecrecursor
    links:
      - recursor
      - dnssecrecursor

  recursor:
    image: pschiffe/pdns-recursor
    environment:
      PDNS_local_address: 0.0.0.0
      PDNS_allow_from: 0.0.0.0/0

  dnssecrecursor:
    image: pschiffe/pdns-recursor
    environment:
      PDNS_local_address: 0.0.0.0
      PDNS_allow_from: 0.0.0.0/0
      PDNS_dnssec: validate

  analysis:
    build:
      context: stuff/
      dockerfile: Dockerfile.analysis
    volumes:
      - .:/app/
    command: bash -c 'cd collector/data/analysis; python -u analysis.py'